In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np

In [7]:
f1=np.arange(1,11)
print(f1)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
g1=f1.reshape(2,5)
print(g1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [9]:
f2=np.arange(1,21)
print(f2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [13]:
extracted_elements=f2[5:16]
print(f2)
print(extracted_elements)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 6  7  8  9 10 11 12 13 14 15 16]


In [15]:
#import pandas library
import pandas as pd

In [35]:
series={'apple':3,'banana':2,'orange':1,'pears':4}
print(series)








{'apple': 3, 'banana': 2, 'orange': 1, 'pears': 4}


In [19]:
data={"name":["sunu","vinu","minu","manu","sulu","sanu","sinu","salu","afu","afi"],
      "age":[20,25,30,27,24,35,40,28,33,29],
      "gender":["female","male","female","male","female","male","female","male","female","male"],
     }
df=pd.DataFrame(data)
print(df)

   name  age  gender
0  sunu   20  female
1  vinu   25    male
2  minu   30  female
3  manu   27    male
4  sulu   24  female
5  sanu   35    male
6  sinu   40  female
7  salu   28    male
8   afu   33  female
9   afi   29    male


In [20]:
df["occupation"]=["programmer","manager","analyst","programmer","manager","analyst","programmer","manager","analyst","programmer"]
print(df)

   name  age  gender  occupation
0  sunu   20  female  programmer
1  vinu   25    male     manager
2  minu   30  female     analyst
3  manu   27    male  programmer
4  sulu   24  female     manager
5  sanu   35    male     analyst
6  sinu   40  female  programmer
7  salu   28    male     manager
8   afu   33  female     analyst
9   afi   29    male  programmer


In [23]:
age_filtered_df=df.query("age>=30")
print(age_filtered_df)

   name  age  gender  occupation
2  minu   30  female     analyst
5  sanu   35    male     analyst
6  sinu   40  female  programmer
8   afu   33  female     analyst


In [25]:
df.to_csv("dataframe.csv")
df_csv=pd.read_csv("dataframe.csv")
print(df_csv)

   Unnamed: 0  name  age  gender  occupation
0           0  sunu   20  female  programmer
1           1  vinu   25    male     manager
2           2  minu   30  female     analyst
3           3  manu   27    male  programmer
4           4  sulu   24  female     manager
5           5  sanu   35    male     analyst
6           6  sinu   40  female  programmer
7           7  salu   28    male     manager
8           8   afu   33  female     analyst
9           9   afi   29    male  programmer
